name: Terraform PR Apply

on:
  pull_request:
    types: [closed]
    branches:
      - main  # o la rama principal que uses

env:
  BUCKET_NAME: "your-tfplans-bucket"  # Cambiar por tu bucket
  AWS_REGION: "eu-west-1"             # Ajustar región según necesites

jobs:
  verify-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write   # Necesario para OIDC
      contents: read    # Necesario para checkout
    outputs:
      pr_number: ${{ github.event.pull_request.number }}
      environment: ${{ steps.set-env.outputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment (puedes modificarlo para obtenerlo de labels, etc.)
        id: set-env
        run: |
          # Ejemplo: obtener entorno de una label del PR
          # ENVIRONMENT=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          #   ${{ github.event.pull_request.issue_url }}/labels | jq -r '.[] | select(.name | match("env-")) | .name' | cut -d'-' -f2)
          # echo "environment=${ENVIRONMENT:-dev}" >> $GITHUB_OUTPUT
          echo "environment=dev" >> $GITHUB_OUTPUT  # Valor por defecto

  apply-terraform:
    needs: verify-merge
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ needs.verify-merge.outputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::557760777793:role/asumir-role-OIDC  # Ajustar ARN
          role-session-name: github-terraform-apply
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="env/${{ needs.verify-merge.outputs.environment }}/backend.tfvars"

      - name: Load tfplan from S3
        run: |
          echo "Loading tfplan for PR ${{ needs.verify-merge.outputs.pr_number }}"
          aws s3 cp s3://${{ env.BUCKET_NAME }}/pr-${{ needs.verify-merge.outputs.pr_number }}/${{ needs.verify-merge.outputs.environment }}-tfplan tfplan

      - name: Terraform Apply
        run: |
          echo "Applying Terraform changes for environment ${{ needs.verify-merge.outputs.environment }}"
          terraform apply -auto-approve tfplan

      - name: Cleanup tfplan from S3
        run: |
          echo "Cleaning up tfplan after apply"
          aws s3 rm s3://${{ env.BUCKET_NAME }}/pr-${{ needs.verify-merge.outputs.pr_number }}/${{ needs.verify-merge.outputs.environment }}-tfplan
