name: Deploy Pipeline

on:
  pull_request:
    types: [opened]

jobs:
  deploy-to-s3:
    permissions:
      id-token: write  
      contents: read   
    uses: ./.github/workflows/terraform-validate.yml  
    with:
      environment: ${{ github.event.pull_request.base.ref }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
