name: Assume role with OIDC
on:
  push:
    branches:
      - main  # Solo se activa en cambios en la rama main

env:
  BUCKET_NAME: "bucket-lambda-rds-example"  # Reemplaza con el nombre de tu bucket S3
  AWS_REGION: "eu-west-1"     # Reemplaza con la región de tu bucket S3

# Permisos necesarios
permissions:
  id-token: write   # Necesario para solicitar el JWT (autenticación con OIDC)
  contents: read    # Necesario para actions/checkout

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::557760777793:role/asumir-role-OIDC
          role-session-name: pruebavodafone
          aws-region: ${{ env.AWS_REGION }}
