name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate
      run: |
        echo "Running validation..."
        terraform validate

    - name: Save tiplan
      run: |
        echo "Saving tiplan..."
        terraform plan -out tf.plan

    - name: Plan
      run: |
        echo "Running plan..."
        aws s3 cp tf.plan s3://${{ env.BUCKET_NAME }}/tf.plan
