name: PR Closed Pipeline

on:
  pull_request:
    types: [closed]
    
env:
  BUCKET_NAME: "bucket-lambda-rds-example"
  AWS_REGION: "eu-west-1"

jobs:
  on-pr-closed:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Necesario para OIDC
      contents: read   # Necesario para checkout
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::557760777793:role/asumir-role-OIDC
          role-session-name: pruebavodafone
          aws-region: ${{ env.AWS_REGION }}

      - name: Run GitHub Action
        run: echo "Running GitHub Action..."

      - name: Remove tiplan
        run: |
          echo "Removing tfplan..."
          aws s3 rm s3://${{ env.BUCKET_NAME }}/tf.plan
