on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  plan-dev:
    uses: ./.github/workflows/terraform-base.yml
    permissions:
      contents: read
      pull-requests: write  # ← Nuevo permiso necesario
      id-token: write
    with:
      environment: 'dev'
      trigger_type: 'plan'
      pr_number: ${{ github.event.number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.DEV_AWS_ROLE_ARN }}

  plan-pre:
    uses: ./.github/workflows/terraform-base.yml
    with:
      environment: 'pre'
      trigger_type: 'plan'
      pr_number: ${{ github.event.number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PRE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PRE_AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.PRE_AWS_ROLE_ARN }}
