name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize]
    
env:
  BUCKET_NAME: "bucket-lambda-rds-example"
  AWS_REGION: "eu-west-1" 
  
permissions:
  id-token: write   # Necesario para solicitar el JWT (autenticación con OIDC)
  contents: read    # Necesario para actions/checkout

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
      with:
        role-to-assume: arn:aws:iam::557760777793:role/asumir-role-OIDC
        role-session-name: pruebavodafone
        aws-region: ${{ env.AWS_REGION }}
      
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"
        
    - name: Initalitation
      run: |
        echo "Running Initalitation..."
        terraform init

    - name: Validate
      run: |
        echo "Running validation..."
        terraform validate

    - name: Save tiplan
      run: |
        echo "Saving tiplan..."
        terraform plan -out tf.plan

    - name: Plan
      run: |
        echo "Running plan..."
        aws s3 cp tf.plan s3://${{ env.BUCKET_NAME }}/tf.plan
