on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  verify-delete:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false
    outputs:
      pr_number: ${{ github.event.pull_request.number }}

    steps:
      - name: Extract PR number
        run: echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

  destroy-dev:
    needs: verify-delete
    uses: ./.github/workflows/terraform-base.yml
    with:
      environment: 'dev'
      trigger_type: 'destroy'
      pr_number: ${{ needs.verify-delete.outputs.pr_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.DEV_AWS_ROLE_ARN }}
