on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  verify-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      pr_number: ${{ github.event.pull_request.number }}

    steps:
      - name: Extract PR number
        run: echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

  apply-dev:
    needs: verify-merge
    uses: ./.github/workflows/terraform-base.yml
    with:
      environment: 'dev'
      trigger_type: 'apply'
      pr_number: ${{ needs.verify-merge.outputs.pr_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.DEV_AWS_ROLE_ARN }}
  
  apply-pre:
    needs: verify-merge
    uses: ./.github/workflows/terraform-base.yml
    with:
      environment: 'pre'
      trigger_type: 'apply'
      pr_number: ${{ needs.verify-merge.outputs.pr_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PRE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PRE_AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.PRE_AWS_ROLE_ARN }}
  
  apply-pro:
    needs: verify-merge
    uses: ./.github/workflows/terraform-base.yml
    with:
      environment: 'pro'
      trigger_type: 'apply'
      pr_number: ${{ needs.verify-merge.outputs.pr_number }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PRO_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PRO_AWS_SECRET_ACCESS_KEY }}
      AWS_ROLE_ARN: ${{ secrets.PRO_AWS_ROLE_ARN }}
