name: Terraform Validate (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ROLE_ARN:
        required: true

permissions:
  id-token: write
  contents: read    

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::557760777793:role/asumir-role-OIDC
          role-session-name: pruebavodafone
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Bucket Name
        run: |
          echo "BUCKET_NAME=bucket-${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Terraform Plan
        run: terraform plan -out tf.plan
