on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      trigger_type:  # 'plan', 'apply', or 'destroy'
        type: string
        required: true
      pr_number:
        type: string
        required: false
        default: ''
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ROLE_ARN:
        required: true

env:
  BUCKET_NAME: "bucket-vodafone-dev"
  AWS_REGION: "eu-west-1"

jobs:
  terraform-execution:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: ${{ inputs.environment }}-session

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init -backend-config="env/${{ inputs.environment }}/backend.tfvars"

      - name: Execute Terraform Command
        run: |
          case "${{ inputs.trigger_type }}" in
            "plan")
              terraform plan -out=tfplan
              aws s3 cp tfplan s3://${{ env.BUCKET_NAME }}/pr-${{ inputs.pr_number }}/${{ inputs.environment }}.tfplan
              ;;
            "apply")
              aws s3 cp s3://${{ env.BUCKET_NAME }}/pr-${{ inputs.pr_number }}/${{ inputs.environment }}.tfplan tfplan
              terraform apply -auto-approve tfplan
              aws s3 rm s3://${{ env.BUCKET_NAME }}/pr-${{ inputs.pr_number }}/${{ inputs.environment }}.tfplan
              ;;
            "destroy")
              terraform destroy -auto-approve
              ;;
          esac
